# This is a basic workflow to help you get started with Actions

name: 02_manual_input_workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name: 
        Description: ' Person to greet'
        default: 'world'
        required: true

jobs: 
  greetbk: 
    runs-on: ubuntu-latest
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Sending greeting 
        run: echo "Hello, ${{ github.event.inputs.name }}"
