# This is a basic workflow to help you get started with Actions

name: 02_manual_input_workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name: 
        Description: ' Person to greet'
        default: 'bk'
        required: true

jobs: 
  greetbk: 
    runs-on: ubuntu-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      # Runs a single command using the runners shell
      - name: Sending greeting bk
        run: echo "Hello, ${{ github.event.inputs.name }}"
