name: Status Check Functions
on: [push]

jobs: 
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: sleep 20
      - name: Runs on Failure
        if: failure()
        run: echo " Runs only on failuer"
      - name: Runs on Success
        if: success()
        run: echo 'Runs on Success'
      - name: Always Runs
        if: always()
        run: echo 'Always Runs'
      - name: Runs when cancelled 
        if: cancelled()
        
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failuer()
    steps:
      - run: echo 'Job2'
    s
    
